# Generated by Django 3.1.4 on 2021-05-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField(default=0)),
                ('background_color', models.CharField(max_length=50)),
                ('font_color', models.CharField(max_length=50)),
            ],
        ),
    ]
