# Generated by Django 3.2.3 on 2021-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField(default=0)),
                ('background_color', models.CharField(max_length=50)),
                ('font_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
